#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(cd "${script_dir}/.." && pwd)"
source_root="${1:-${repo_dir}/..}"
output_path="${repo_dir}/csrc/extensions/generated_legacy_api_manifest.inc"

sources=(
  "cuda:${source_root}/csrc/torch_bindings.cpp"
  "cpu:${source_root}/csrc/cpu/torch_bindings.cpp"
  "rocm:${source_root}/csrc/rocm/torch_bindings.cpp"
  "moe:${source_root}/csrc/moe/torch_bindings.cpp"
  "stable:${source_root}/csrc/libtorch_stable/torch_bindings.cpp"
)

tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"' EXIT

{
  printf '%s\n' '// Generated by tools/sync_legacy_api_manifest.sh.'
  printf '%s\n' '// This file is checked in so `nkernels` retains the exported method surface'
  printf '%s\n' '// during refactors. Update it with the sync script when the legacy bindings'
  printf '%s\n' '// change.'

  for entry in "${sources[@]}"; do
    domain="${entry%%:*}"
    path="${entry#*:}"

    if [[ ! -f "${path}" ]]; then
      continue
    fi

    printf '\n// %s\n' "${domain}"
    perl -0777 -ne '
      while (/(?:ops|cache_ops|cuda_utils|custom_ar|rocm_ops|m)\.def\(\s*"([^"]+)"/sg) {
        $s = $1;
        $s =~ s/\(.+$//s;
        $s =~ s/\($//;
        next if $s eq q{};
        print "$s\n";
      }
    ' "${path}" | sort -u | while IFS= read -r method; do
      printf 'NKERNELS_API_METHOD("%s", "%s")\n' "${domain}" "${method}"
    done
  done
} > "${tmp_file}"

awk '!seen[$0]++' "${tmp_file}" > "${output_path}"
